(let* ((h1 (small::find-obj-with-props (scaffold tile)
						  `((:i . ,(- *2r* i)) (:k . ,prevk))))
		  (h2 (small::find-obj-with-props (scaffold tile)
						  `((:i . ,(+ (- *2r* i) 1)) (:k . ,prevk))))
		  (h3 (small::find-obj-with-props (scaffold tile)
						  `((:i . ,i) (:k . ,k))))
		  (h4 (small::find-obj-with-props (scaffold tile)
						  `((:i . ,(+ i 1)) (:k . ,k))))
		  (stap (create-staple
			 `((:obj ,h1  :start 12 :end 20  :from-3end t)
			   (:obj ,h2  :start 0 :end 11  :from-3end nil)
			   (:single-strand t)
			   (:obj ,h3  :start 0  :end 11 :from-3end t)
			   (:obj ,h4  :start 12  :end 20 :from-3end nil)))))
	     stap)
